### PR TITLE
Adds minimal support for invoice_number parameter

### PR DESCRIPTION
**Pull request by irumiha**
In some configurations authorize.net will allow repeated transactions with the same card and amount if you send different invoice_numbers. This pull request gives minimal support for that feature.

### CODE REVIEW

**Comment by elahmo** [comment]
+1 for this, I was lookin on how to add an invoice number to the transaction details and stumbled upon this PR.

**Comment by jeffschenck** [comment]
Sorry for the delayed answer, @irumiha — been a busy couple weeks — and thanks for the PR! Can you point to anywhere in the docs or forums that explains how the repeat transactions are handled with and without the invoice number? 

Part of the design philosophy behind the AuthorizeSauce library is to keep it as thin as possible — to use your own app's code to store all the descriptions and whatnot, and to only have AuthorizeSauce do with Authorize.net what you can't possibly do on your own. So for this pull request, I would love to be certain this is the only way to allow multiple similar charges to succeed, and whether all fields are required or just invoice number, which would allow us to do away with description and purchase order number. 

If it ends up that there's truly a common use case that is only achievable with an invoice field, then I'm not against including it, but we'd also want testing separately for transactions with and without the info, as well as documentation of the functionality.

**Comment by irumiha** [comment]
Well, I have a client that has this peculiar situation where they might have several credit card transactions in the very short timespan with the same credit card. Something like a reseller network where each reseller handles cash with the end user and uses his own credit card in our billing platform. Long story short, they tell me that they reached an agreement with Authorize.net where repeat transactions on the same card but with different invoice_numbers won't be flagged as duplicate. This was direct interaction with Authorize.net's customer support so I can not point to any public documents that describe this behaviour.
Anyways, I thought I might ease some of the deployment pains from my coworkers by submitting this patch to the official library.

**Comment by elahmo** [comment]
I also have a need to assign an Invoice number to the transaction, so in the backend the sales person can actually check or correlate the sales with invoice numbers. So +1 from me for this.

I am using this for normal transactions, not recurring ones.

Any chance of this being merged or?

**Comment by joshkel** [comment]
Confirmation in the official docs is found in the [AIM Developer Guide](http://www.authorize.net/support/AIM_guide.pdf), "Response for Duplicate Transactions," page 52:
> You can specify the period (“window”) of time after a transaction is submitted during which the payment gateway checks for a duplicate transaction (based on credit card number, *invoice number*, amount, billing address information, transaction type, etc.) using the duplicate window field [emphasis added].

So changing the invoice number is enough to keep a transaction from being flagged as a duplicate.

The docs provide further details on what happens when a transaction is flagged as a duplicate.

**Comment by jeffschenck** [comment]
Thanks for pointing to the relevant docs. Based on this reading, it looks like the ``x_duplicate_window`` parameter is the more direct and straightforward way to get the behavior we're looking for here. If we add support for this, you should be able to control duplicate allowed/disallowed behavior more directly and precisely than with the transaction_id. 

This sounds like the most appropriate solution to me, and I'd be very open to it if anyone has time to put it together in a pull request. I'm still not sold on invoice_number being a fit with the design philosophy for this library (as explained above), since it really boils down to just a way to store and retrieve information, which is better handled in your own datastore, rather than in Authorize.net.

**Comment by joshkel** [comment]
I don't agree that `x_duplicate_window` is a more direct solution.

If I use an invoice number, then I have absolute control over whether a transaction is a duplicate: if it's the same invoice number, it's a duplicate (as long as it's within the window), and if it's a different number, it's never a duplicate.

If I use the duplicate window, it's less direct, since it relies on the timings of otherwise identical transactions. And it seems not exactly obvious - maybe I'm just being paranoid, but I wasn't sure if two transactions that arrived within the same second would be interpreted as falling in a 0-second-length window, and I had to read the docs a couple of times and run a couple of tests to satisfy myself that setting the window to 0 would have the desired result of never flagging duplicates.

A secondary consideration is that my client is used to logging into the Authorize.net web interface (for example, to void transactions), and being able to present the invoice number there may be helpful. This is really a minor point for my purposes - I don't know if they use the invoice number in particular, and my app can link to the Authorize.net transaction ID, so they have an alternate way of matching transactions - but it's an example of where storing information to Authorize.net has benefit, beyond using it as a datastore for my own application.

With all of that said - it's your library, and I doubt I have enough experience with the Authorize.net interface to critique its design philosophy. Just my 2 cents' worth.

**Comment by jeffschenck** [comment]
Well, I'm not 100% sold personally. But this library's not just for me — there seems to be enough reason and enough desire for ``x_invoice_num`` support that I'm comfortable bringing it in to the library. This pull request, however, is not actually "minimal support" as it claims to be. 

If anyone is motivated to add support for just ``x_invoice_num``, I would happily include it. For now, though, I'm closing this PR out. Thanks!

**Pull request closed without merging**
